main: com.cccece.authwithqq.AuthwithQQPlugin
name: AuthwithQQ
version: "${VERSION}"
api-version: "1.16" # Targeting Paper 1.16+
author: cc_cece
description: Authorize and bind using QQ.
permissions:
  qqbinding.admin:
    description: Allows console to use /qqbindsuccess (Deprecated)
    default: op